### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by ibalhk** [DougHennig/SFMail#10]
## 📝 Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by ibalhk** [comment]
We tried SFmail.prg but it has some error while building-compilation project below….
Program z:\utilities\sfmail\sfmail.prg has the following errors:     Unknown STREXTRACT - Undefined
And
Program z:\utilities\sfmail\wwdotnetbridge.prg has the following errors:     Unknown ADDPROPERTY - Undefined

Then when we run also get error like “16 Unrecognized command verb 209 try sfmail1.sendmail.smtp “

Anybody ‘s recommendation or suggestion / help is highly appreciable

Struggling to make it work!

Thanking you a lot in advance

**Comment by ibalhk** [comment]
wwwdotnetbridge.prg = When compile in VFP Version 6.0 have below erros.
Compiling wwdotnetbridge.prg
LOCAL loArray as Westwind.WebConnection.ComArray
Error in line 408: Must be a variable or array.
LOCAL loBridge as Westwind.wwDotNetBridge
Error in line 448: Must be a variable or array.
LOCAL loArray as Westwind.WebConnection.ComArray
Error in line 451: Must be a variable or array.
LOCAL loVal as Westwind.WebConnnection.ComValue
Error in line 1267: Must be a variable or array.

Unknown ADDPROPERTY - Undefined

please help

**Comment by DougHennig** [comment]
SFMail requires VFP 9.

**Comment by ibalhk** [comment]
Sir,

 �

Thank you so very much for your kind email and reply.

 �

Well noted , however we do not have VFP Ver9 & cant find in the market

 �

Is there any other suggestion to use with VFP 6.0, please help us in suggesting with your valuable comments.

 �

Kind Regards,

Ashwani Bansal

 �

**Comment by DougHennig** [comment]
You could try the Chilkat library (Google it to find the web site).

**Comment by ibalhk** [comment]
Sir,

 �

Thank you and I manage to install my VFP9 with SP2 pack, when I run my project with SFmail, it give me an error…may be seems I made some mistake

 �

12 Variable ‘THIS TRY’ is not found

208 …SFmail.SENDMAIL.SMTP

 �

However below is part of the Sfmai.prg

protected procedure SendMailSMTP

                                local loBridge, ;

                                                lcPath, ;

                                                loMail, ;

                                                laAttachments[1], ;

                                                lnAttachments, ;

                                                lnI, ;

                                                llReturn, ;

                                                loAuth, ;

                                                loException as Exception

                                with Thistry

 �

Attached sfmail,prg

 �

Your help suggestion would be a great help

 �

Thank you si very much

 �

Kind Regards,

Ashwani Bansal

 �

 �

**Comment by DougHennig** [comment]
You must have removed the carriage return after the WITH THIS statement. Here is the code that is in the repository:

![image](https://github.com/user-attachments/assets/312a7a1f-838d-4b02-b306-b9dcd959d2a2)

**Comment by ibalhk** [comment]
Sir

I am sorry to disturb you, Thank you for our kind help, i edited sfmail.prg, removed the carriage return, there is o compilation error, however when I run my app and calling sfmail, it gives me error

 �



 �



 �

Code now looks like 

 �

                protected procedure SendMailSMTP

                                local loBridge, ;

                                                lcPath, ;

                                                loMail, ;

                                                laAttachments[1], ;

                                                lnAttachments, ;

                                                lnI, ;

                                                llReturn, ;

                                                loAuth, ;

                                                loException as Exception

                                with This

                                                try

 �

 �

* Get an instance of wwDotNetBridge and load the assembly.

 �

                                                                do wwDotNetBridge

                                                                loBridge = GetwwDotNetBridge()

                                                                lcPath   = ''

                                                                if not file('SMTPLibrary2.dll')

                                                                                lcPath = .GetAppFolder()

                                                                endif not file('SMTPLibrary2.dll')

                                                                loBridge.LoadAssembly(lcPath + 'SMTPLibrary2.dll')

 �

 �

Thank you Sir

 �

BR/Ashwani

 �

 �

**Comment by DougHennig** [comment]
There are no images attached so I do not know what the error message is.

**Comment by ibalhk** [comment]
Sorry Sir,

 

Attached with this

 

Thank you so very much

 

BR/Ashwani

**Comment by DougHennig** [comment]
Still no image. Instead of replying via email, post directly to this issue on GitHub.

**Comment by ibalhk** [comment]
Sir,

Thank you and I manage to install my VFP9 with SP2 pack, when I run my project with SFmail, it give me an error…may be seems I made some mistake

12 Variable ‘THIS TRY’ is not found
208 …SFmail.SENDMAIL.SMTP

However below is part of the Sfmai.prg
protected procedure SendMailSMTP
                                local loBridge, ;
                                                lcPath, ;
                                                loMail, ;
                                                laAttachments[1], ;
                                                lnAttachments, ;
                                                lnI, ;
                                                llReturn, ;
                                                loAuth, ;
                                                loException as Exception
                                with Thistry

Attached sfmail,prg

Your help suggestion would be a great help

Thank you si very much

Kind Regards,
Ashwani Bansal
![SFMAILFIRSTERROR](https://github.com/user-attachments/assets/2a5b6114-b4cd-403e-9d0d-bdca4d13b5d4)
![SFMAILSECONDERROR](https://github.com/user-attachments/assets/9ac01613-473c-4d65-926b-85a9479db2fc)

**Comment by ibalhk** [comment]
Sorry forgot to attach sfmail.prg

Or Sir, if you have latest version of Sfmail.prg, can i request to copy and i use the same to test, would be a great help!

Thank you

**Comment by ibalhk** [comment]
Good Day Sir,
I again tried your suggestion and now when run the app, select to send email i get below run time error..

"Message not sent : Cannot find entry point SetClrVersion in the DLL."

Attached the screen shot

Please guide

Thank you Sir

![SfmailErrorruntime3](https://github.com/user-attachments/assets/24935a23-aa1c-466f-a1b2-0506dd32b4b4)

**Comment by DougHennig** [comment]
This is not an issue with SFMail; it is an issue with wwDotNetBridge, which SFMail uses. See https://www.west-wind.com/wconnect/weblog/ShowEntry.blog?id=897 for assistance with this.

**Comment by ibalhk** [comment]
Sir,
Thank you for your kind help and well noted, I have posted my issue on above West Wind link, waiting for their reply.

Just one question is it must to use wwDotNetBridge with SFmail to send out the email message?

Thank you for your help always.

Kind Regards,
Ashwani Bansal

**Comment by DougHennig** [comment]
Yes.
